name: Update Manoj.pdf in S3

on:
  push:
    branches: [ main ]
    paths:
      - "Manoj.pdf"          # Triggers only when Manoj.pdf changes
  workflow_dispatch:

env:
  AWS_REGION: ap-south-1
  S3_BUCKET: mybucket10072025
  LOCAL_FILE: Manoj.pdf
  S3_KEY: Manoj.pdf          # File name inside S3

jobs:
  upload-resume:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Upload updated resume to S3
      run: |
        aws s3 cp "$LOCAL_FILE" "s3://$S3_BUCKET/$S3_KEY" \
          --content-type application/pdf
